<h1 align='center'>Линейная алгебра</h1>

<h1 align='center'>Домашнее задание № 2</h1>

## Матрицы и матричные операции. Часть 1

In [11]:
import numpy as np

# <p style="background-color:lightgreen;font-family:newtimeroman;color:#662e2e;font-size:130%;text-align:center;border-radius:30px 30px;">Задача 1</p>

__1.__ Установите, какие произведения матриц $AB$ и $BA$ определены, и найдите размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

**Решение:**  

__Матрицей__ размера $m\times n$ называется прямоугольная таблица, состоящая из $m$ строк и $n$ столбцов.
  
__Условие перемножение матриц: важно, чтобы число столбцов матрицы $A$ было равно числу строк матрицы $B$.__  
  
Определить оба произведения $A\cdot B$ и $B\cdot A$ можно только тогда, когда число столбцов $A$ совпадает с числом строк $B$, а число строк $A$ — с числом столбцов $B$. В этом случае матрицы $A\cdot B$ и $B\cdot A$ будут квадратными. Их порядок в общем случае будет различным и совпадать только при квадратных матрицах $A$ и $B$.

 а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$  
$$A = \begin{pmatrix}
a_{11} & a_{12}\\
a_{21} & a_{22}\\
a_{31} & a_{32}\\
a_{41} & a_{42}\\
\end{pmatrix}  
B = \begin{pmatrix}
b_{11} & b_{12}\\
b_{21} & b_{22}\\
b_{31} & b_{32}\\
b_{41} & b_{42}\\
\end{pmatrix}$$  
В данном случае ни одно из произведений $A\cdot B$ и $B\cdot A$ определить невозможно, т.к. не выполняется условие перемножение матриц.

In [2]:
A = np.random.randint(10, size=(4, 2))
B = np.random.randint(10, size=(4, 2))

print(f'Матрица A\n{A}\nМатрица B\n{B}')

Матрица A
[[2 6]
 [4 4]
 [0 9]
 [5 3]]
Матрица B
[[7 8]
 [7 1]
 [3 0]
 [8 4]]


In [4]:
print(f'Произведение матриц AB равно:\n {np.dot(A, B)}')

ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

In [5]:
print(f'Произведение матриц BA равно:\n {np.dot(B, A)}')

ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$  

$$A = \begin{pmatrix}
a_{11} & a_{12} & a_{13} & a_{14} & a_{15}\\
a_{21} & a_{22} & a_{23} & a_{24} & a_{25}\\
\end{pmatrix}  
B = \begin{pmatrix}
b_{11} & b_{12} & b_{13}\\
b_{21} & b_{22} & b_{23}\\
b_{31} & b_{32} & b_{33}\\
b_{41} & b_{42} & b_{43}\\
b_{51} & b_{52} & b_{53}\\
\end{pmatrix}$$  
В данном случае определено произведение $A\cdot B$, т.к. при $B\cdot A$ не выполняется условие перемножение матриц. Матрица $AB$ будет иметь размер 2Х3. 

In [6]:
A = np.random.randint(10, size=(2, 5))
B = np.random.randint(10, size=(5, 3))

print(f'Матрица A\n{A}\nМатрица B\n{B}')

Матрица A
[[5 6 6 9 1]
 [4 5 9 9 0]]
Матрица B
[[8 6 0]
 [2 8 4]
 [6 8 1]
 [1 2 2]
 [0 5 0]]


In [7]:
print(f'Произведение матриц AB равно:\n {np.dot(A, B)}')

Произведение матриц AB равно:
 [[ 97 149  48]
 [105 154  47]]


In [8]:
print(f'Произведение матриц BA равно:\n {np.dot(B, A)}')

ValueError: shapes (5,3) and (2,5) not aligned: 3 (dim 1) != 2 (dim 0)

в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$  

$$A = \begin{pmatrix}
a_{11} & a_{12} & a_{13}\\
a_{21} & a_{22} & a_{23}\\
a_{31} & a_{32} & a_{33}\\
a_{41} & a_{42} & a_{43}\\
a_{51} & a_{52} & a_{53}\\
a_{61} & a_{62} & a_{63}\\
a_{71} & a_{72} & a_{73}\\
a_{81} & a_{82} & a_{83}\\
\end{pmatrix}  
B = \begin{pmatrix}
b_{11} & b_{12} & b_{13} b_{14} & b_{15} & b_{16} & b_{17} & b_{18}\\
b_{21} & b_{22} & b_{23} b_{24} & b_{25} & b_{26} & b_{27} & b_{28}\\
b_{31} & b_{32} & b_{33} b_{34} & b_{35} & b_{36} & b_{37} & b_{38}\\
\end{pmatrix}$$    

В данном случае определены оба произведения $AB$ и $BA$. Матрица $AB$ будет иметь размер 8Х8, а $BA$ - 3Х3. 

In [9]:
A = np.random.randint(10, size=(8, 3))
B = np.random.randint(10, size=(3, 8))

print(f'Матрица A\n{A}\nМатрица B\n{B}')

Матрица A
[[0 8 5]
 [8 8 0]
 [1 3 5]
 [7 2 4]
 [5 0 8]
 [9 3 3]
 [1 2 8]
 [3 1 4]]
Матрица B
[[7 1 1 2 8 6 0 2]
 [3 4 6 2 1 0 8 3]
 [5 5 8 9 5 6 1 8]]


In [10]:
print(f'Произведение матриц AB равно:\n {np.dot(A, B)}')

Произведение матриц AB равно:
 [[49 57 88 61 33 30 69 64]
 [80 40 56 32 72 48 64 40]
 [41 38 59 53 36 36 29 51]
 [75 35 51 54 78 66 20 52]
 [75 45 69 82 80 78  8 74]
 [87 36 51 51 90 72 27 51]
 [53 49 77 78 50 54 24 72]
 [44 27 41 44 45 42 12 41]]


In [11]:
print(f'Произведение матриц BA равно:\n {np.dot(B, A)}')

Произведение матриц BA равно:
 [[123  91 138]
 [ 74  97 137]
 [215 150 199]]


г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$

$$A = \begin{pmatrix}
a_{11} & a_{12} & a_{13} & a_{14}\\
a_{21} & a_{22} & a_{23} & a_{24}\\
a_{31} & a_{32} & a_{33} & a_{34}\\
a_{41} & a_{42} & a_{43} & a_{44}\\
\end{pmatrix}  
B = \begin{pmatrix}
b_{11} & b_{12} & b_{13} & b_{14}\\
b_{21} & b_{22} & b_{23} & b_{24}\\
b_{31} & b_{32} & b_{33} & b_{34}\\
b_{41} & b_{42} & b_{43} & b_{44}\\
\end{pmatrix}$$    

В данном случае определены оба произведения $AB$ и $BA$. Матрица $AB$ будет иметь размер 4Х4, и $BA$ также 4Х4. 

In [12]:
A = np.random.randint(10, size=(4, 4))
B = np.random.randint(10, size=(4, 4))

print(f'Матрица A\n{A}\nМатрица B\n{B}')

Матрица A
[[4 4 9 1]
 [0 1 1 6]
 [7 7 4 8]
 [7 2 8 8]]
Матрица B
[[4 2 9 0]
 [4 1 8 1]
 [0 3 7 5]
 [2 6 5 4]]


In [13]:
print(f'Произведение матриц AB равно:\n {np.dot(A, B)}')

Произведение матриц AB равно:
 [[ 34  45 136  53]
 [ 16  40  45  30]
 [ 72  81 187  59]
 [ 52  88 175  74]]


In [14]:
print(f'Произведение матриц BA равно:\n {np.dot(B, A)}')

Произведение матриц BA равно:
 [[ 79  81  74  88]
 [ 79  75  77  82]
 [ 84  62  71 114]
 [ 71  57  76 110]]


# <p style="background-color:lightgreen;font-family:newtimeroman;color:#662e2e;font-size:130%;text-align:center;border-radius:30px 30px;">Задача 2</p>

__2.__ Найдите сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

**Решение:**  

$$A + B = 
\begin{pmatrix}
1 & -2\\
3 & 0\\
\end{pmatrix} + \begin{pmatrix}
4 & -1\\
0 & 5\\
\end{pmatrix} = \begin{pmatrix}
1 + 4 & (-2) + (-1)\\
3 + 0 & 0 + 5\\
\end{pmatrix}
= \begin{pmatrix}
5 & -3\\
3 & 5\\
\end{pmatrix}.$$  

$$A \cdot B = 
\begin{pmatrix}
1 & -2\\
3 & 0\\
\end{pmatrix} \cdot \begin{pmatrix}
4 & -1\\
0 & 5\\
\end{pmatrix} = \begin{pmatrix}
(1\cdot4 + (-2)\cdot0) & (1\cdot(-1) + (-2)\cdot5)\\ 
(3\cdot4 + 0\cdot0) & (3\cdot(-1) + 0\cdot5)
\end{pmatrix}
= \begin{pmatrix}
4 & -11\\
12 & -3\\
\end{pmatrix}.$$  

In [15]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'Матрица A\n{A}\nМатрица B\n{B}')

Матрица A
[[ 1 -2]
 [ 3  0]]
Матрица B
[[ 4 -1]
 [ 0  5]]


In [16]:
print(f'Сумма матриц A + B равна:\n {A + B}')

Сумма матриц A + B равна:
 [[ 5 -3]
 [ 3  5]]


In [17]:
print(f'Произведение матриц AB равно:\n {np.dot(A, B)}')

Произведение матриц AB равно:
 [[  4 -11]
 [ 12  -3]]


# <p style="background-color:lightgreen;font-family:newtimeroman;color:#662e2e;font-size:130%;text-align:center;border-radius:30px 30px;">Задача 3</p>

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислите линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

**Решение:**  

$$D = 3A-2B+4C = 3\cdot\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} - 2\cdot\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix} + 4\cdot\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} = \begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix} - \begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix} + \begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix} = \begin{pmatrix}
3-0+8 & 21-10-16\\ 
9-4+4 & -18+2+4
\end{pmatrix} = \begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$$

In [18]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

print(f'Матрица A\n{A}\nМатрица B\n{B}\nатрица C\n{C}')

Матрица A
[[ 1  7]
 [ 3 -6]]
Матрица B
[[ 0  5]
 [ 2 -1]]
атрица C
[[ 2 -4]
 [ 1  1]]


In [19]:
D = 3*A - 2*B + 4*C

print(f'Матрица D = 3A-2B+4C равна\n{D}')

Матрица D = 3A-2B+4C равна
[[ 11  -5]
 [  9 -12]]


# <p style="background-color:lightgreen;font-family:newtimeroman;color:#662e2e;font-size:130%;text-align:center;border-radius:30px 30px;">Задача 4</p>

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислите $AA^{T}$ и $A^{T}A$.

**Решение:**  

Транспонированная матрица — это матрица, отражённая относительно главной диагонали, на которой располагаются элементы с $i=j$. При транспонировании строки исходной матрицы становятся столбцами, а столбцы — строками.

$$A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}, \;A^{T}=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}.$$

In [20]:
A = np.array([[4, 1], [5, -2], [2, 3]])

print(f'Матрица A\n{A}')

Матрица A
[[ 4  1]
 [ 5 -2]
 [ 2  3]]


In [21]:
A_t = A.T

print(f'Транспонированная матрица A^t равна:\n {A_t}')

Транспонированная матрица A^t равна:
 [[ 4  5  2]
 [ 1 -2  3]]


In [22]:
print(f'Произведение матриц AA^t равно:\n {np.dot(A, A_t)}')

Произведение матриц AA^t равно:
 [[17 18 11]
 [18 29  4]
 [11  4 13]]


In [23]:
print(f'Произведение матриц A^tA равно:\n {np.dot(A_t, A)}')

Произведение матриц A^tA равно:
 [[45  0]
 [ 0 14]]


# <p style="background-color:lightgreen;font-family:newtimeroman;color:#662e2e;font-size:130%;text-align:center;border-radius:30px 30px;">Задача 5</p>

__5*.__ Напишите на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

**Решение:**  

In [33]:
a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]

In [34]:
def dot_matrix(a, b):
    try: #  если размер матриц соответствует условиям умножения, то работаем. Иначе выводим сообщение об ошибке 
        result_matrix = [[0 for _ in range(len(a))] for _ in range(len(b[0]))] #  создаем новую матрицу необходимого размера 
        for i in range(len(a)):
            for j in range(len(a[0])):
                for k in range(len(b[0])):
                    result_matrix[i][k] = a[i][j] * b[j][k] + result_matrix[i][k]  #  заполнение итоговой матрицы
        print(*result_matrix, sep='\n') #  вывод на печать столбиком
                 
    except IndexError:
        print('Условие перемножения матриц AxB: число столбцов матрицы A должно быть равно числу строк матрицы B')
     

In [35]:
dot_matrix(a, b)

[30, 24, 18]
[84, 69, 54]
[138, 114, 90]


In [36]:
# проверка
AB = np.dot(a, b)
AB

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

## Матрицы и матричные операции. Часть 2

# <p style="background-color:lightgreen;font-family:newtimeroman;color:#662e2e;font-size:130%;text-align:center;border-radius:30px 30px;">Задача 1</p>

__1.__ Вычислите определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$


In [28]:
import numpy as np
import math

**Решение:**  

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = sinxsinx + cosxcosx = sinx^2 + cosx^2 = 1 $$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 4 \cdot 5 \cdot 9 = 180$$

In [29]:
#b

b = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Матрица:\n{b}')
print(f'Оперделитель матрицы b: {np.linalg.det(b):.0f}')

Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Оперделитель матрицы b: 180


   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = \begin{vmatrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & -6 & -12
\end{vmatrix} = \begin{vmatrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & 0 & 0
\end{vmatrix} = 0$$

In [30]:
#в

с = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{с}')
print(f'Оперделитель матрицы с: {np.linalg.det(с):.0f}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Оперделитель матрицы с: -0


# <p style="background-color:lightgreen;font-family:newtimeroman;color:#662e2e;font-size:130%;text-align:center;border-radius:30px 30px;">Задача 2</p>

__2.__ Определитель матрицы $A$ равен $4$. Найдите:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

**Решение:**  

  а) $det(A^{2}) = det(A) \cdot det(A) = 4 \cdot 4 = 16$;
    
   б) $det(A^{T}) = det(A) = 4$;
    
   в) $det(2A) = 2^{n} \cdot det(A) = 2^{n} \cdot 4$, где n - размер матрицы.

# <p style="background-color:lightgreen;font-family:newtimeroman;color:#662e2e;font-size:130%;text-align:center;border-radius:30px 30px;">Задача 3</p>

__3.__  Докажите, что матрица:

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

**Решение:**  

Матрица называется _сингулярной_ или _вырожденной_, если её определитель равен нулю.

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$  

Сложем первую строку матрицы, умноженную на 2, со второй:  

$$\begin{pmatrix}
-2 & 7 & -3\\ 
0 & 0 & 0\\ 
-3 & 7 & 13
\end{pmatrix}$$  

В соответствии со свойствами определителя, если матрица имеет нулевую строку или столбец, то определитель равен нулю.  
Следовательно,  
$$\begin{vmatrix}
-2 & 7 & -3\\ 
0 & 0 & 0\\ 
-3 & 7 & 13
\end{vmatrix} = 0$$  

Соответственно, матрица является вырожденной.

In [31]:
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Матрица:\n{a}')
determinant = np.linalg.det(a)
if determinant == 0:
    print('Определитель матрицы равен 0, следовательно матрица является вырожденной')
else:
    print('Определитель матрицы не равен 0, следовательно матрица не является вырожденной')

Матрица:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
Определитель матрицы равен 0, следовательно матрица является вырожденной


# <p style="background-color:lightgreen;font-family:newtimeroman;color:#662e2e;font-size:130%;text-align:center;border-radius:30px 30px;">Задача 4</p>

__4.__ Найдите ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

**Решение:**  

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$  

Третья строка является суммой первых двух. Значит, её можно отбросить.  

$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix};$  

Из первой строки можно вычесть вторую и поменять их местами  

$\begin{pmatrix}
1 & 1 & 1\\ 
0 & 1 & 2
\end{pmatrix};$  

Таким образом, ранг матрицы равен 2.

In [32]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
r = np.linalg.matrix_rank(a)
print(f'Матрица:\n{a}')
print(f'Ранг матрицы: {r}')

Матрица:
[[1 2 3]
 [1 1 1]
 [2 3 4]]
Ранг матрицы: 2


   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}$  

Третья строка является суммой первых двух. Значит, её можно отбросить.  

$\begin{pmatrix}
2 & 3 & 5 & 6\\
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2
\end{pmatrix}$ 

Из третьей строки вычитаем вторую  

$\begin{pmatrix}
2 & 3 & 5 & 6\\
0 & 0 & 2 & 1\\ 
0 & 0 & 0 & 1
\end{pmatrix}$  

Таким образом, ранг матрицы равен 3.

In [33]:
b = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
r = np.linalg.matrix_rank(b)
print(f'Матрица:\n{b}')
print(f'Ранг матрицы: {r}')

Матрица:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]
Ранг матрицы: 3
