<h1 align='center'>Линейная алгебра</h1>

<h1 align='center'>Практическое задание № 4</h1>

## Системы линейных уравнений. Часть 1

In [1]:
import numpy as np
import scipy
from scipy import linalg
from scipy.linalg import solve_triangular
import pprint

# <p style="background-color:lightgreen;font-family:newtimeroman;color:#662e2e;font-size:130%;text-align:center;border-radius:30px 30px;">Задача 1</p>

__1.__ Решите систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

**Решение:**  

In [2]:
def _gauss_method(a, b, n):
    rank_a = np.linalg.matrix_rank(a)
    a_extended = np.concatenate((a, b), axis=1)
    rank_a_extended = np.linalg.matrix_rank(a_extended)
    n = n
    if rank_a == rank_a_extended == n:
        print(f'Ранг матрицы коэффициентов: {rank_a},\nРанг расширенной матрицы: {rank_a_extended},\nЧисло неизвестных: {n}')
        print(f'rankA = rankA~ = n\nСистема совместна и имеет единственное решение')
    elif rank_a == rank_a_extended and rank_a < n:
        print(f'Ранг матрицы коэффициентов: {rank_a},\nРанг расширенной матрицы: {rank_a_extended},\nЧисло неизвестных: {n}')
        print(f'rankA = rankA~ < n\nСистема совместна и имеет бесконечное количество решений')
    else:
        print(f'Ранг матрицы коэффициентов: {rank_a},\nРанг расширенной матрицы: {rank_a_extended},\nЧисло неизвестных: {n}')
        print(f'rankA < rankA~\nСистема несовместна')

In [3]:

a = np.array([[1, 1, -1, -2], [2, 1, -1, 1], [1, 1, -3, 1]])
b = np.array([0, -2, 4]).reshape(-1,1)
n = 4
# a, b
_gauss_method(a, b, n)

Ранг матрицы коэффициентов: 3,
Ранг расширенной матрицы: 3,
Число неизвестных: 4
rankA = rankA~ < n
Система совместна и имеет бесконечное количество решений



$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$ 

Матрица коэффициентов системы:
$$A=\begin{pmatrix}
1 & 1 & -1 & -2 \\
2 & 1 & -1 & 1 \\
1 & 1 & -3 & 1
\end{pmatrix};$$

Вектор-столбец неизвестных:
$$x = \begin{pmatrix}
x_1\\
x_2\\
x_3\\
x_4
\end{pmatrix};$$  

Вектор-столбец правых частей (свободных членов системы):  
$$b = \begin{pmatrix}
0\\
-2\\
4
\end{pmatrix};$$  

Расширенная матрица:  
$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\
2 & 1 & -1 & 1 \\
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\
-2\\
4
\end{matrix}
\end{pmatrix}$$  



Из 3-го уравнения вычтем первое:  
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\
2 & 1 & -1 & 1 \\
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\
-2\\
4
\end{matrix}
\end{pmatrix}
\rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\
2 & 1 & -1 & 1 \\
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\
-2\\
4
\end{matrix}
\end{pmatrix}$$  

1-е уравнение умножим на 2 и вычтем из 2-го:  

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\
2 & 1 & -1 & 1 \\
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\
-2\\
4
\end{matrix}
\end{pmatrix}
\rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\
0 & -1 & 1 & 5 \\
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\
-2\\
4
\end{matrix}
\end{pmatrix}
$$  

Оставшаяся матрица соответствует системе: 
$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
-x_{2}+x_{3}+5x_{4}=-2, \\
-2x_{3}+3x_{4}=4.
\end{cases}$$  

Последнее уравнение содержит две неизвестных. Неизвестные, «сидящие» на ступеньках матрицы, принято называть _базисными_, и их надо выразить через _свободные_ неизвестные. В этом случае можно рассматривать в качестве _свободного_ параметра $x_{4}=c$. Тогда, выражая остальные переменные через $c$, получим:

$$x_{4}=c,$$
$$-2x_{3}+3c=4 \; \Leftrightarrow \; x_{3}=-2 + 1.5c,$$
$$-x_{2}+(-2 + 1.5c)+5c=-2 \; \Leftrightarrow \; x_{2}=6.5c,$$
$$x_{1}+6.5c-(-2 + 1.5c)-2c=0 \; \Leftrightarrow \; x_{1}=-2-4c.$$  

Таковым будет _общее решение системы_. Подставляя произвольные числа вместо $c$, мы получим _частное решение_. Например, при $c=0$:

$$x_{1}=-2,$$
$$x_{2}=0,$$
$$x_{3}=-2,$$
$$x_{4}=0.$$


# <p style="background-color:lightgreen;font-family:newtimeroman;color:#662e2e;font-size:130%;text-align:center;border-radius:30px 30px;">Задача 2</p>

__2.__ Проверьте на совместность и выясните, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

**Решение:**  

In [4]:
#а
a = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
b = np.array([[4], [-17], [0]])
n = 3
_gauss_method(a, b, n)

Ранг матрицы коэффициентов: 3,
Ранг расширенной матрицы: 3,
Число неизвестных: 3
rankA = rankA~ = n
Система совместна и имеет единственное решение


In [5]:
#б
a = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
b = np.array([[1], [-2], [5]])
n = 3
_gauss_method(a, b, n)

Ранг матрицы коэффициентов: 1,
Ранг расширенной матрицы: 2,
Число неизвестных: 3
rankA < rankA~
Система несовместна


In [6]:
#в
a = np.array([[1, 2, 5], [3, 1, -8]])
b = np.array([[4], [-2]])
n = 3
_gauss_method(a, b, n)

Ранг матрицы коэффициентов: 2,
Ранг расширенной матрицы: 2,
Число неизвестных: 3
rankA = rankA~ < n
Система совместна и имеет бесконечное количество решений


# <p style="background-color:lightgreen;font-family:newtimeroman;color:#662e2e;font-size:130%;text-align:center;border-radius:30px 30px;">Задача 3</p>

__3.__ Проверьте на совместность и выясните, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей:

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

**Решение:**  

In [7]:
a = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
b = np.array([[3], [2], [4], [1]])
n = 4
_gauss_method(a, b, n)

Ранг матрицы коэффициентов: 4,
Ранг расширенной матрицы: 4,
Число неизвестных: 4
rankA = rankA~ = n
Система совместна и имеет единственное решение


In [8]:
np.linalg.solve(a, b)

array([[2.76666667],
       [0.3       ],
       [1.33333333],
       [0.5       ]])

# <p style="background-color:lightgreen;font-family:newtimeroman;color:#662e2e;font-size:130%;text-align:center;border-radius:30px 30px;">Задача 4</p>

__4.__ Дана система линейных уравнений, заданная расширенной матрицей:

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найдите соотношение между параметрами $a$, $b$ и $c$, при которых система считается несовместной.

**Решение:**  

In [9]:
# матрица коэффициентов
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# ранг матирца а
np.linalg.matrix_rank(a)

2

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}$$

Из 2-го уравнения вычтем первое, умноженное на 4:  
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\
b\\
c
\end{matrix}
\end{pmatrix}
\rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\
b-4a\\
c
\end{matrix}
\end{pmatrix}$$  

Из 3-го уравнения вычтем первое, умноженное на 7:  
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\
b-4a\\
c
\end{matrix}
\end{pmatrix}
\rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & -6 & -12
\end{matrix}\right|
\begin{matrix}
a\\
b-4a\\
c-7a
\end{matrix}
\end{pmatrix}$$  

Из 3-го уравнения вычтем второе, умноженное на 2:  
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & -6 & -12
\end{matrix}\right|
\begin{matrix}
a\\
b-4a\\
c-7a
\end{matrix}
\end{pmatrix}
\rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\
b-4a\\
c-2b+a
\end{matrix}
\end{pmatrix}$$  

Чтобы система была несовместной, должно выполнятсья условие $rankA<rank \tilde A$.  
Для этого $c-2b+a \ne 0$.  

Ответ: Система будет считаться несовместной при всех $a, b, c$, кроме $c = 2b-a$.



## Системы линейных уравнений. Часть 2

# <p style="background-color:lightgreen;font-family:newtimeroman;color:#662e2e;font-size:130%;text-align:center;border-radius:30px 30px;">Задача 1</p>

__1.__ Решите систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

**Решение:**  

a)
$$\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$$


In [11]:
A = np.array([[1, -2],[3, -4]])
b = np.array([1, 7]).reshape(-1, 1)
A, b

(array([[ 1, -2],
        [ 3, -4]]),
 array([[1],
        [7]]))

In [12]:
det_A = np.linalg.det(A)
det_A

2.0000000000000004

$detA \ne 0$, следовательно, система совместна.  
Найдём определители $detA_{1}$, $detA_{2}$:

In [13]:
det_A1 = np.linalg.det(np.hstack((b, A[:,1].reshape(-1, 1))))
det_A2 = np.linalg.det(np.hstack((A[:,0].reshape(-1, 1), b)))
det_A1, det_A2

(9.999999999999998, 4.0)

Найдём решение по формулам Крамера:  
    $$x_{i}=\frac{detA_{i}}{detA},$$

In [14]:
x1 = det_A1 / det_A
x1

4.999999999999998

In [15]:
x2 = det_A2 / det_A
x2

1.9999999999999996

In [16]:
np.linalg.solve(A, b)

array([[5.],
       [2.]])

   б) 
   $$\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$$

In [17]:
A = np.array([[2, -1, 5],[1, 1, -3], [2, 4, 1]])
b = np.array([10, -2, 1]).reshape(-1, 1)
A, b

(array([[ 2, -1,  5],
        [ 1,  1, -3],
        [ 2,  4,  1]]),
 array([[10],
        [-2],
        [ 1]]))

In [18]:
det_A = np.linalg.det(A)
det_A

42.99999999999998

$detA \ne 0$, следовательно, система совместна.  
Найдём определители $detA_{1}$, $detA_{2}$, $detA_{3}$:

In [19]:
det_A1 = np.linalg.det(np.hstack((b, A[:,1:])))
det_A2 = np.linalg.det(np.hstack((A[:,:1], b, A[:,-1:])))
det_A3 = np.linalg.det(np.hstack((A[:,:2], b)))
det_A1, det_A2, det_A3

(86.00000000000004, -43.000000000000014, 42.99999999999998)

Найдём решение по формулам Крамера:  
    $$x_{i}=\frac{detA_{i}}{detA},$$

In [20]:
x1 = det_A1 / det_A
x1

2.0000000000000018

In [21]:
x2 = det_A2 / det_A
x2

-1.0000000000000009

In [22]:
x3 = det_A3 / det_A
x3

1.0

In [23]:
np.linalg.solve(A, b)

array([[ 2.],
       [-1.],
       [ 1.]])

# <p style="background-color:lightgreen;font-family:newtimeroman;color:#662e2e;font-size:130%;text-align:center;border-radius:30px 30px;">Задача 2</p>

__2*.__ Найдите $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

**Решение:**  

   а)
    $$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$

In [24]:
A = np.array([[1, 2, 4],[2, 9, 12],[3, 26, 30]])
p, l, u = scipy.linalg.lu(A)

print('A:')
pprint.pprint(A)

print('P — матрица перестановок:')
pprint.pprint(p)

print('L — нижняя треугольная с единичными диагональными элементами:')
pprint.pprint(l)

print('U — верхняя треугольная:')
pprint.pprint(u)

A:
array([[ 1,  2,  4],
       [ 2,  9, 12],
       [ 3, 26, 30]])
P — матрица перестановок:
array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])
L — нижняя треугольная с единичными диагональными элементами:
array([[1.        , 0.        , 0.        ],
       [0.66666667, 1.        , 0.        ],
       [0.33333333, 0.8       , 1.        ]])
U — верхняя треугольная:
array([[ 3.        , 26.        , 30.        ],
       [ 0.        , -8.33333333, -8.        ],
       [ 0.        ,  0.        ,  0.4       ]])


$U = \begin{pmatrix}
3 & 26 & 30 \\
2 & 9 & 12 \\ 
1 & 2 & 4 \\ 
\end{pmatrix}$

$L = \begin{pmatrix} 
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{pmatrix}$

$U = \begin{pmatrix}
3 & 26 & 30 \\
0 & - \frac{25}{3} & -8 \\ 
0 & -\frac{20}{3} & -6 \\ 
\end{pmatrix}$

$U = \begin{pmatrix}
3 & 26 & 30 \\
0 & -8 \frac{1}{3} & -8 \\ 
0 & 0 & \frac{2}{5} \\ 
\end{pmatrix}$

$L = \begin{pmatrix} 
1 & 0 & 0 \\
\frac{2}{3} & 1 & 0 \\
\frac{1}{3} & \frac{4}{5} & 1
\end{pmatrix}$

   б)
   $$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

In [25]:
A = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])
p, l, u = scipy.linalg.lu(A)

print('A:')
pprint.pprint(A)

print('P — матрица перестановок:')
pprint.pprint(p)

print('L — нижняя треугольная с единичными диагональными элементами:')
pprint.pprint(l)

print('U — верхняя треугольная:')
pprint.pprint(u)

A:
array([[ 1,  1,  2,  4],
       [ 2,  5,  8,  9],
       [ 3, 18, 29, 18],
       [ 4, 22, 53, 33]])
P — матрица перестановок:
array([[0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.]])
L — нижняя треугольная с единичными диагональными элементами:
array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.5       ,  1.        ,  0.        ,  0.        ],
       [ 0.75      , -0.25      ,  1.        ,  0.        ],
       [ 0.25      ,  0.75      , -0.17073171,  1.        ]])
U — верхняя треугольная:
array([[  4.        ,  22.        ,  53.        ,  33.        ],
       [  0.        ,  -6.        , -18.5       ,  -7.5       ],
       [  0.        ,   0.        , -15.375     ,  -8.625     ],
       [  0.        ,   0.        ,   0.        ,  -0.09756098]])


$U = \begin{pmatrix}
4 & 22 & 53 & 33 \\
2 & 5 & 8 & 9 \\ 
3 & 18 & 29 & 18 \\
1 & 1 & 2 & 4
\end{pmatrix}
\rightarrow
\begin{pmatrix}
4 & 22 & 53 & 33 \\
0 & -6 & -18 \frac{1}{2} & -7 \frac{1}{2} \\ 
0 & 1 \frac{1}{2} & -10 \frac{3}{4} & -6 \frac{3}{4} \\
0 & -4 \frac{1}{2} & -11 \frac{1}{4} & -4 \frac{1}{4} 
\end{pmatrix}
\rightarrow
\begin{pmatrix}
4 & 22 & 53 & 33 \\
0 & -6 & -18 \frac{1}{2} & -7 \frac{1}{2} \\ 
0 & 1 \frac{1}{2} & -10 \frac{3}{4} & -6 \frac{3}{4} \\
0 & -4 \frac{1}{2} & -11 \frac{1}{4} & -4 \frac{1}{4} 
\end{pmatrix}
\rightarrow
\begin{pmatrix}
4 & 22 & 53 & 33 \\
0 & -6 & -18 \frac{1}{2} & -7 \frac{1}{2} \\ 
0 & 0 & -15 \frac{3}{8} & -8 \frac{5}{8} \\
0 & 0 & 2 \frac{5}{8} & 1 \frac{3}{8} 
\end{pmatrix}
\rightarrow
\begin{pmatrix}
4 & 22 & 53 & 33 \\
0 & -6 & -18 \frac{1}{2} & -7 \frac{1}{2} \\ 
0 & 0 & -15 \frac{3}{8} & -8 \frac{5}{8} \\
0 & 0 & 0 & - \frac{4}{41}
\end{pmatrix}$

$L = \begin{pmatrix} 
1 & 0 & 0 & 0 \\
\frac{1}{2} & 1 & 0 & 0 \\
\frac{3}{4} & -\frac{1}{4} & 1 & 0 \\
\frac{1}{4} & \frac{3}{4} & - \frac{7}{41} & 1
\end{pmatrix}$

# <p style="background-color:lightgreen;font-family:newtimeroman;color:#662e2e;font-size:130%;text-align:center;border-radius:30px 30px;">Задача 3</p>

__3*.__ Решите систему линейных уравнений методом $LU$-разложения:

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

**Решение:**  

In [26]:
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
b =np.array([1, -6, -5])
p, l, u = scipy.linalg.lu(A)

print('A:')
pprint.pprint(A)

print('P — матрица перестановок:')
pprint.pprint(p)

print('L — нижняя треугольная с единичными диагональными элементами:')
pprint.pprint(l)

print('U — верхняя треугольная:')
pprint.pprint(u)

A:
array([[ 2,  1,  3],
       [11,  7,  5],
       [ 9,  8,  4]])
P — матрица перестановок:
array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])
L — нижняя треугольная с единичными диагональными элементами:
array([[ 1.        ,  0.        ,  0.        ],
       [ 0.81818182,  1.        ,  0.        ],
       [ 0.18181818, -0.12      ,  1.        ]])
U — верхняя треугольная:
array([[11.        ,  7.        ,  5.        ],
       [ 0.        ,  2.27272727, -0.09090909],
       [ 0.        ,  0.        ,  2.08      ]])


In [27]:
lu, piv = linalg.lu_factor(A)
x = linalg.lu_solve((lu, piv), b)

In [28]:
print(f' x_1 = {x[0]}\n x_2 = {x[1]}\n x_3 = {x[2]}')

 x_1 = -1.0000000000000002
 x_2 = 2.4424906541753446e-16
 x_3 = 1.0


$U = \begin{pmatrix}
11 & 7 & 5 \\
9 & 8 & 4 \\
2 & 1 & 3
\end{pmatrix}
\rightarrow
\begin{pmatrix}
11 & 7 & 5 \\
0 & \frac{25}{11} & - \frac{1}{11} \\
0 & - \frac{3}{11} & \frac{23}{11}  
\end{pmatrix}
\rightarrow
\begin{pmatrix}
11 & 7 & 5 \\
0 & \frac{25}{11} & - \frac{1}{11} \\
0 & 0 & \frac{52}{25}  
\end{pmatrix}$

$L = \begin{pmatrix} 
1 & 0 & 0 \\
\frac{9}{11} & 1 & 0 \\
\frac{2}{11} & - \frac{3}{25} & 1
\end{pmatrix} $

$\begin{cases}
y_{1} = -6, \\
\frac{9}{11} y_{1} + y_{2} =-5, \\
\frac{2}{11}y_{1} - \frac{3}{25} y_{2} + y_{3} = 1.
\end{cases}$

$y_{1} = -6$  
$y_{2} = -\frac{1}{11}$  
$y_{3} = \frac{52}{25}$  

$Ux=y:$

$\begin{cases}
11x_{1} + 7x_{2} + 5x_{3} = -6, \\
\frac{25}{11} x_{2} - \frac{1}{11} x_{3}= - \frac{1}{11}, \\
\frac{52}{25} x_{3} = \frac{52}{25}
\end{cases}$

$x_{1} = -1$    
$x_{2} = 0$  
$x_{3} = 1$  

$2 \cdot (-1) + 0 + 3 \cdot 1 = 1$  
$11 \cdot (-1) + 7 \cdot 0 + 5 \cdot 1 = -6$  
$9 \cdot (-1) + 8 \cdot 0 + 4 \cdot 1 = -5$  

# <p style="background-color:lightgreen;font-family:newtimeroman;color:#662e2e;font-size:130%;text-align:center;border-radius:30px 30px;">Задача 4</p>

__4*.__ Решите систему линейных уравнений методом Холецкого:

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

**Решение:**  

In [29]:
A = np.matrix([[81, -45, 45],
               [-45, 50, -15],
               [45, -15, 38]])
b = np.array  ([531, -460, 193])
 
#Разложение Холецкого
for i in range(10000):
    L = np.linalg.cholesky(A)
    Y = solve_triangular(L, b, lower = True, check_finite = False)
    X = solve_triangular(L, Y, lower = True, trans = 1, check_finite = False)

print(f' x_1 = {X[0]}\n x_2 = {X[1]}\n x_3 = {X[2]}')

 x_1 = 6.0
 x_2 = -5.0
 x_3 = -4.0


$\begin{pmatrix}
81 & -45 & 45 \\
-45 & 50 & -15 \\
45 & -15 & 38
\end{pmatrix}$

Произведём разложение на $LL^{T}$:  
    
$l_{11} =\sqrt{a_{11}} = \sqrt{81} = 9$  
$l_{21} =\frac{a_{21}}{l_{11}} = \frac{-45}{9} = -5$  
$l_{31} =\frac{a_{31}}{l_{11}} = \frac{45}{9} = 5$  

$l_{22} = \sqrt{a_{22}-l_{21}^{2}} = \sqrt{50 - (-5)^2} = 5$  
$l_{32} = \frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right) = \frac{1}{5}(-15 - (-5) \cdot 5) = 2$

$l_{33} = \sqrt{a_{33}-l_{32}^{2}-l_{31}^{2}} = \sqrt{38 - 2^2 - 5^2} = 3$

Получили матрицу:  
    
$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}, 
\; \; 
L^{T} = \begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2\\ 
0 & 0 & 3
\end{pmatrix}.$

Решим систему $Ly=b:$  

$\begin{cases}
    9 y_1 = 531 \\
    -5 y_1 + 5 y_2 = -460 \\
    5 y_1 + 2 y_2 + 3 y_3 = 193
\end{cases}$

$y_1 = 59$  
$y_2 = -33$  
$y_3 = -12$  

И решим систему $L^{T}x=y:$  

$\begin{cases}
    9 x_1 - 5 x_2 + 5 x_3 = 59 \\
    5 x_2 + 2 x_3 = -33 \\
    3 x_3 = -12
\end{cases}$

$x_1 = 6$  
$x_2 = -5$  
$x_3 = -4$  

Осуществим проверку, подставив полученные значения в исходную систему:  

$\begin{cases}
    81 \cdot 6 - 45 \cdot (-5) + 45 \cdot (-4) = 531 \\
    -45 \cdot 6 + 50 \cdot (-5) - 15 \cdot (-4) = -460 \\
    45 \cdot 6 - 15 \cdot (-5) + 38 \cdot (-4) = 193
\end{cases}$

# <p style="background-color:lightgreen;font-family:newtimeroman;color:#662e2e;font-size:130%;text-align:center;border-radius:30px 30px;">Задача 5</p>

__5*.__ Напишите на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.